cache: pip

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

matrix:
  fast_finish: true
  include:
    # - python: "3.5"
    #   env: TOXENV=py35
    # - python: "3.6"
    #   env: TOXENV=py36
    # - os: linux
    #   dist: xenial
    #   python: "3.7"
    #   env: TOXENV=py37
    #   sudo: true
    # - python: "3.5"
    #   env: TOXENV=lint
    - if: branch = translationDocs AND type = push
      os: linux
      dist: xenial
      python: "3.7"
      sudo: true
      install:
        - pip install qiskit
        - pip install -r requirements-dev.txt
        - pip install sphinx-intl
      script:
        - if [[ $TRAVIS_COMMIT_MESSAGE == *"Test travis"* ]]; then tools/test.sh ; fi ;
        - tools/deploy_documentation.sh
    - if: tag IS present
      python: "3.6"
      env:
        - TWINE_USERNAME=qiskit
      install: pip install -U twine
      script:
        - python3 setup.py sdist
        - twine upload dist/qiskit*tar.gz

language: python
install: pip install -U tox
script:
  - tox

notifications:
  email: false
