cache: pip

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

      before_install:
  - >-
    openssl aes-256-cbc -K $encrypted_a301093015c6_key -iv $encrypted_a301093015c6_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key

matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - os: linux
      dist: xenial
      python: "3.7"
      env: TOXENV=py37
      sudo: true
    - python: "3.5"
      env: TOXENV=lint
    - if: branch = translationDocs AND type = push
      os: linux
      dist: xenial
      python: "3.7"
      sudo: true
      install:
        - pip install qiskit
        - pip install -r requirements-dev.txt
      script: tools/deploy_documentation.sh

language: python
install: pip install -U tox
script:
  - tox

notifications:
  email: false
